[2023-03-05T13:00:13.467+0000] {processor.py:153} INFO - Started process (PID=165) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:00:13.472+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:00:13.500+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:00:13.499+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:00:13.546+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:00:13.544+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:00:13.548+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:00:13.585+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.127 seconds
[2023-03-05T13:00:44.444+0000] {processor.py:153} INFO - Started process (PID=402) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:00:44.447+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:00:44.448+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:00:44.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:00:44.464+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:00:44.462+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:00:44.466+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:00:44.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.063 seconds
[2023-03-05T13:01:14.889+0000] {processor.py:153} INFO - Started process (PID=625) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:01:14.897+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:01:14.901+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:01:14.900+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:01:14.924+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:01:14.922+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:01:14.924+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:01:14.953+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.075 seconds
[2023-03-05T13:01:45.982+0000] {processor.py:153} INFO - Started process (PID=860) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:01:45.985+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:01:45.988+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:01:45.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:01:46.005+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:01:46.003+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:01:46.006+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:01:46.059+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.104 seconds
[2023-03-05T13:02:01.908+0000] {processor.py:153} INFO - Started process (PID=1072) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:02:01.918+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:02:01.920+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:02:01.919+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:02:01.945+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:02:01.942+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:02:01.945+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:02:01.989+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.088 seconds
[2023-03-05T13:02:32.807+0000] {processor.py:153} INFO - Started process (PID=1308) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:02:32.814+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:02:32.817+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:02:32.817+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:02:32.986+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:02:32.978+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:02:32.989+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:02:33.375+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.600 seconds
[2023-03-05T13:03:03.844+0000] {processor.py:153} INFO - Started process (PID=1531) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:03:03.847+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:03:03.850+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:03:03.850+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:03:03.880+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:03:03.876+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:03:03.882+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:03:03.940+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.143 seconds
[2023-03-05T13:03:34.145+0000] {processor.py:153} INFO - Started process (PID=1756) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:03:34.150+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:03:34.160+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:03:34.158+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:03:34.180+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:03:34.177+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:03:34.181+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:03:34.338+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.203 seconds
[2023-03-05T13:04:04.525+0000] {processor.py:153} INFO - Started process (PID=1992) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:04:04.528+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:04:04.529+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:04:04.529+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:04:04.544+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:04:04.542+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:04:04.545+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:04:04.583+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.066 seconds
[2023-03-05T13:04:35.520+0000] {processor.py:153} INFO - Started process (PID=2216) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:04:35.523+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:04:35.524+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:04:35.524+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:04:35.538+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:04:35.536+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:04:35.539+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:04:35.582+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.069 seconds
[2023-03-05T13:05:05.895+0000] {processor.py:153} INFO - Started process (PID=2452) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:05:05.897+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:05:05.898+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:05:05.898+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:05:05.931+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:05:05.928+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:05:05.932+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:05:05.975+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.087 seconds
[2023-03-05T13:05:36.765+0000] {processor.py:153} INFO - Started process (PID=2675) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:05:36.768+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:05:36.774+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:05:36.774+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:05:36.801+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:05:36.798+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:05:36.802+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:05:36.876+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.121 seconds
[2023-03-05T13:06:07.983+0000] {processor.py:153} INFO - Started process (PID=2910) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:06:07.986+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:06:07.987+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:06:07.987+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:06:08.020+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:06:08.017+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:06:08.024+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:06:08.062+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.088 seconds
[2023-03-05T13:06:38.430+0000] {processor.py:153} INFO - Started process (PID=3134) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:06:38.505+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:06:38.568+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:06:38.567+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:06:40.021+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:06:39.993+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:06:40.028+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:06:40.485+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 2.249 seconds
[2023-03-05T13:07:11.309+0000] {processor.py:153} INFO - Started process (PID=3370) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:07:11.311+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:07:11.313+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:07:11.312+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:07:11.334+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:07:11.330+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'spotify_etl'
[2023-03-05T13:07:11.336+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:07:11.392+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.091 seconds
[2023-03-05T13:07:41.820+0000] {processor.py:153} INFO - Started process (PID=3594) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:07:41.823+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:07:41.825+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:07:41.825+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:07:43.206+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:07:43.198+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 10, in <module>
    'start_date': datetime(2023, 3, 5),
NameError: name 'datetime' is not defined
[2023-03-05T13:07:43.208+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:07:43.285+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 1.476 seconds
[2023-03-05T13:08:13.664+0000] {processor.py:153} INFO - Started process (PID=3829) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:08:13.667+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:08:13.668+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:08:13.668+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:08:13.943+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:08:13.939+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 10, in <module>
    'start_date': datetime(2023, 3, 5),
NameError: name 'datetime' is not defined
[2023-03-05T13:08:13.943+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:08:13.964+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.317 seconds
[2023-03-05T13:08:44.130+0000] {processor.py:153} INFO - Started process (PID=4054) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:08:44.132+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:08:44.133+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:08:44.133+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:08:44.605+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:08:44.600+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 10, in <module>
    'start_date': datetime(2023, 3, 5),
NameError: name 'datetime' is not defined
[2023-03-05T13:08:44.606+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:08:44.633+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.496 seconds
[2023-03-05T13:09:15.273+0000] {processor.py:153} INFO - Started process (PID=4289) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:09:15.276+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:09:15.278+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:09:15.278+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:09:15.517+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:09:15.510+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 10, in <module>
    'start_date': datetime(2023, 3, 5),
NameError: name 'datetime' is not defined
[2023-03-05T13:09:15.520+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:09:15.552+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.285 seconds
[2023-03-05T13:09:46.430+0000] {processor.py:153} INFO - Started process (PID=4513) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:09:46.431+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:09:46.432+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:09:46.432+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:09:46.730+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:09:46.725+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 10, in <module>
    'start_date': datetime(2023, 3, 5),
NameError: name 'datetime' is not defined
[2023-03-05T13:09:46.731+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:09:46.755+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.330 seconds
[2023-03-05T13:09:49.533+0000] {processor.py:153} INFO - Started process (PID=4519) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:09:49.536+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:09:49.537+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:09:49.537+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:09:49.583+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:09:49.575+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:09:49.585+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:09:49.646+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.133 seconds
[2023-03-05T13:10:20.445+0000] {processor.py:153} INFO - Started process (PID=4757) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:10:20.447+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:10:20.449+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:10:20.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:10:20.467+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:10:20.465+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:10:20.468+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:10:20.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.073 seconds
[2023-03-05T13:10:51.555+0000] {processor.py:153} INFO - Started process (PID=4980) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:10:51.557+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:10:51.559+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:10:51.558+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:10:51.576+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:10:51.574+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:10:51.577+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:10:51.604+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.061 seconds
[2023-03-05T13:11:21.724+0000] {processor.py:153} INFO - Started process (PID=5217) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:11:21.727+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:11:21.730+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:11:21.729+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:11:21.752+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:11:21.749+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:11:21.752+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:11:21.793+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.075 seconds
[2023-03-05T13:11:52.812+0000] {processor.py:153} INFO - Started process (PID=5441) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:11:52.815+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:11:52.816+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:11:52.816+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:11:52.831+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:11:52.829+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:11:52.832+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:11:52.872+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.065 seconds
[2023-03-05T13:12:23.315+0000] {processor.py:153} INFO - Started process (PID=5677) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:12:23.317+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:12:23.319+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:12:23.319+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:12:23.333+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:12:23.331+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:12:23.333+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:12:23.363+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.055 seconds
[2023-03-05T13:12:53.482+0000] {processor.py:153} INFO - Started process (PID=5901) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:12:53.484+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:12:53.486+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:12:53.486+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:12:53.504+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:12:53.501+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:12:53.505+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:12:53.552+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.074 seconds
[2023-03-05T13:13:24.020+0000] {processor.py:153} INFO - Started process (PID=6137) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:13:24.023+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:13:24.024+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:13:24.024+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:13:24.039+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:13:24.037+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:13:24.039+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:13:24.079+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.065 seconds
[2023-03-05T13:13:54.327+0000] {processor.py:153} INFO - Started process (PID=6363) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:13:54.330+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:13:54.332+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:13:54.331+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:13:54.353+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:13:54.351+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:13:54.354+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:13:54.389+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.071 seconds
[2023-03-05T13:14:24.766+0000] {processor.py:153} INFO - Started process (PID=6598) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:14:24.772+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:14:24.775+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:14:24.775+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:14:24.806+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:14:24.801+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:14:24.807+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:14:24.856+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.099 seconds
[2023-03-05T13:14:55.381+0000] {processor.py:153} INFO - Started process (PID=6822) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:14:55.383+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:14:55.385+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:14:55.384+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:14:55.410+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:14:55.406+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:14:55.410+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:14:55.480+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.104 seconds
[2023-03-05T13:15:26.585+0000] {processor.py:153} INFO - Started process (PID=7057) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:15:26.587+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:15:26.588+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:15:26.588+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:15:26.615+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:15:26.610+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:15:26.616+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:15:26.653+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.075 seconds
[2023-03-05T13:15:57.352+0000] {processor.py:153} INFO - Started process (PID=7281) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:15:57.355+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:15:57.356+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:15:57.356+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:15:57.389+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:15:57.385+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:15:57.390+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:15:57.451+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.110 seconds
[2023-03-05T13:16:28.181+0000] {processor.py:153} INFO - Started process (PID=7505) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:16:28.189+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:16:28.196+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:16:28.195+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:16:28.245+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:16:28.241+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:16:28.246+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:16:28.301+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.140 seconds
[2023-03-05T13:16:58.470+0000] {processor.py:153} INFO - Started process (PID=7741) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:16:58.477+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:16:58.479+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:16:58.479+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:16:58.505+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:16:58.503+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:16:58.506+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:16:58.533+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.067 seconds
[2023-03-05T13:17:29.133+0000] {processor.py:153} INFO - Started process (PID=7965) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:17:29.135+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:17:29.136+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:17:29.136+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:17:29.149+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:17:29.147+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:17:29.150+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:17:29.175+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.050 seconds
[2023-03-05T13:18:01.047+0000] {processor.py:153} INFO - Started process (PID=8200) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:18:01.073+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:18:01.125+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:18:01.109+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:18:01.644+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:18:01.620+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:18:01.650+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:18:01.915+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 1.094 seconds
[2023-03-05T13:18:32.687+0000] {processor.py:153} INFO - Started process (PID=8424) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:18:32.691+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:18:32.694+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:18:32.693+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:18:32.724+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:18:32.719+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:18:32.727+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:18:32.775+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.098 seconds
[2023-03-05T13:19:03.430+0000] {processor.py:153} INFO - Started process (PID=8648) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:19:03.433+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:19:03.434+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:19:03.434+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:19:03.461+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:19:03.457+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:19:03.463+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:19:03.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.076 seconds
[2023-03-05T13:19:34.108+0000] {processor.py:153} INFO - Started process (PID=8872) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:19:34.112+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:19:34.114+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:19:34.114+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:19:34.141+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:19:34.136+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:19:34.145+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:19:34.232+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.149 seconds
[2023-03-05T13:20:05.808+0000] {processor.py:153} INFO - Started process (PID=9105) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:20:05.830+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:20:05.848+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:20:05.847+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:20:06.161+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:20:06.069+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:20:06.191+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:20:06.563+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.796 seconds
[2023-03-05T13:20:36.986+0000] {processor.py:153} INFO - Started process (PID=9332) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:20:36.989+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:20:36.991+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:20:36.991+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:20:37.019+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:20:37.016+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:20:37.020+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:20:37.069+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.096 seconds
[2023-03-05T13:21:07.195+0000] {processor.py:153} INFO - Started process (PID=9556) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:21:07.197+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:21:07.199+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:21:07.199+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:21:07.222+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:21:07.219+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:21:07.223+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:21:07.258+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.070 seconds
[2023-03-05T13:21:37.880+0000] {processor.py:153} INFO - Started process (PID=9792) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:21:37.882+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:21:37.884+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:21:37.884+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:21:37.900+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:21:37.898+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:21:37.900+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:21:37.927+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.067 seconds
[2023-03-05T13:22:08.281+0000] {processor.py:153} INFO - Started process (PID=10028) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:22:08.283+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:22:08.285+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:22:08.285+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:22:08.303+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:22:08.300+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:22:08.304+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:22:08.333+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.067 seconds
[2023-03-05T13:22:38.475+0000] {processor.py:153} INFO - Started process (PID=10252) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:22:38.478+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:22:38.483+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:22:38.483+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:22:38.506+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:22:38.504+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:22:38.507+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:22:38.540+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.074 seconds
[2023-03-05T13:23:08.921+0000] {processor.py:153} INFO - Started process (PID=10487) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:23:08.924+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:23:08.925+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:23:08.925+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:23:08.948+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:23:08.945+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:23:08.949+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:23:08.976+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.061 seconds
[2023-03-05T13:23:39.099+0000] {processor.py:153} INFO - Started process (PID=10714) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:23:39.102+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:23:39.108+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:23:39.108+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:23:39.136+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:23:39.133+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:23:39.137+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:23:39.167+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.075 seconds
[2023-03-05T13:24:09.460+0000] {processor.py:153} INFO - Started process (PID=10948) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:24:09.467+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:24:09.469+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:24:09.469+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:24:09.532+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:24:09.526+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:24:09.534+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:24:09.580+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.135 seconds
[2023-03-05T13:24:40.628+0000] {processor.py:153} INFO - Started process (PID=11175) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:24:40.630+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:24:40.631+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:24:40.631+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:24:40.653+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:24:40.646+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:24:40.658+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:24:40.687+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.066 seconds
[2023-03-05T13:25:11.531+0000] {processor.py:153} INFO - Started process (PID=11410) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:25:11.542+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:25:11.544+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:25:11.544+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:25:11.589+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:25:11.582+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:25:11.590+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:25:11.621+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.097 seconds
[2023-03-05T13:25:41.817+0000] {processor.py:153} INFO - Started process (PID=11634) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:25:41.820+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:25:41.821+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:25:41.821+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:25:41.855+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:25:41.852+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:25:41.856+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:25:41.898+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.088 seconds
[2023-03-05T13:26:12.113+0000] {processor.py:153} INFO - Started process (PID=11870) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:26:12.114+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:26:12.115+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:26:12.115+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:26:12.127+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:26:12.125+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:26:12.128+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:26:12.160+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.052 seconds
[2023-03-05T13:26:42.720+0000] {processor.py:153} INFO - Started process (PID=12095) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:26:42.723+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:26:42.725+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:26:42.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:26:42.750+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:26:42.747+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:26:42.750+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:26:42.781+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.079 seconds
[2023-03-05T13:27:13.541+0000] {processor.py:153} INFO - Started process (PID=12331) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:27:13.544+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:27:13.545+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:27:13.545+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:27:13.559+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:27:13.556+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:27:13.561+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:27:13.601+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.066 seconds
[2023-03-05T13:27:44.032+0000] {processor.py:153} INFO - Started process (PID=12554) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:27:44.034+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:27:44.035+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:27:44.035+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:27:44.053+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:27:44.050+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:27:44.054+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:27:44.099+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.075 seconds
[2023-03-05T13:28:14.592+0000] {processor.py:153} INFO - Started process (PID=12790) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:28:14.595+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:28:14.596+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:28:14.596+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:28:14.627+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:28:14.618+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:28:14.629+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:28:14.690+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.104 seconds
[2023-03-05T13:28:45.065+0000] {processor.py:153} INFO - Started process (PID=13014) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:28:45.067+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:28:45.068+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:28:45.068+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:28:45.084+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:28:45.082+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:28:45.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:28:45.122+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.075 seconds
[2023-03-05T13:29:15.735+0000] {processor.py:153} INFO - Started process (PID=13249) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:29:15.742+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:29:15.747+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:29:15.747+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:29:15.766+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:29:15.764+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:29:15.768+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:29:15.831+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.127 seconds
[2023-03-05T13:29:46.830+0000] {processor.py:153} INFO - Started process (PID=13473) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:29:46.833+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:29:46.835+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:29:46.835+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:29:46.853+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:29:46.851+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:29:46.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:29:46.898+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.082 seconds
[2023-03-05T13:30:17.355+0000] {processor.py:153} INFO - Started process (PID=13709) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:30:17.358+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:30:17.359+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:30:17.359+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:30:17.371+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:30:17.369+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:30:17.371+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:30:17.411+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.062 seconds
[2023-03-05T13:30:47.745+0000] {processor.py:153} INFO - Started process (PID=13933) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:30:47.747+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:30:47.749+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:30:47.749+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:30:47.774+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:30:47.771+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:30:47.776+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:30:47.808+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.070 seconds
[2023-03-05T13:31:18.132+0000] {processor.py:153} INFO - Started process (PID=14168) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:31:18.136+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:31:18.140+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:31:18.140+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:31:18.164+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:31:18.160+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:31:18.164+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:31:18.211+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.088 seconds
[2023-03-05T13:31:48.927+0000] {processor.py:153} INFO - Started process (PID=14391) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:31:48.929+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:31:48.931+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:31:48.931+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:31:48.953+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:31:48.948+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:31:48.954+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:31:48.999+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.078 seconds
[2023-03-05T13:32:19.829+0000] {processor.py:153} INFO - Started process (PID=14627) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:32:19.834+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:32:19.836+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:32:19.835+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:32:19.854+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:32:19.851+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:32:19.854+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:32:19.904+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.089 seconds
[2023-03-05T13:32:50.242+0000] {processor.py:153} INFO - Started process (PID=14852) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:32:50.244+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:32:50.246+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:32:50.245+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:32:50.276+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:32:50.272+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:32:50.277+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:32:50.310+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.074 seconds
[2023-03-05T13:33:20.890+0000] {processor.py:153} INFO - Started process (PID=15088) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:33:20.893+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:33:20.895+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:33:20.895+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:33:20.928+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:33:20.923+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:33:20.930+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:33:20.972+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.096 seconds
[2023-03-05T13:33:51.537+0000] {processor.py:153} INFO - Started process (PID=15320) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:33:51.543+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:33:51.547+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:33:51.547+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:33:51.604+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:33:51.597+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:33:51.613+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:33:51.738+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.235 seconds
[2023-03-05T13:34:22.296+0000] {processor.py:153} INFO - Started process (PID=15549) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:34:22.300+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:34:22.302+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:34:22.302+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:34:22.325+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:34:22.322+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:34:22.326+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:34:22.363+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.073 seconds
[2023-03-05T13:34:52.595+0000] {processor.py:153} INFO - Started process (PID=15773) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:34:52.597+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:34:52.598+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:34:52.598+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:34:52.619+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:34:52.616+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:34:52.619+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:34:52.659+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.070 seconds
[2023-03-05T13:35:26.941+0000] {processor.py:153} INFO - Started process (PID=15995) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:35:26.945+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:35:26.946+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:35:26.946+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:35:26.965+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:35:26.960+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:35:26.968+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:35:27.009+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.074 seconds
[2023-03-05T13:35:57.942+0000] {processor.py:153} INFO - Started process (PID=16210) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:35:57.946+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:35:57.949+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:35:57.948+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:35:57.980+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:35:57.976+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:35:57.981+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:35:58.031+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.100 seconds
[2023-03-05T13:36:28.183+0000] {processor.py:153} INFO - Started process (PID=16446) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:36:28.186+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:36:28.190+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:36:28.190+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:36:28.201+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:36:28.200+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:36:28.202+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:36:28.222+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.043 seconds
[2023-03-05T13:36:59.122+0000] {processor.py:153} INFO - Started process (PID=16681) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:36:59.127+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:36:59.131+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:36:59.130+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:36:59.177+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:36:59.157+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:36:59.181+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:36:59.269+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.156 seconds
[2023-03-05T13:37:29.612+0000] {processor.py:153} INFO - Started process (PID=16904) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:37:29.616+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:37:29.617+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:37:29.617+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:37:29.630+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:37:29.626+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:37:29.631+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:37:29.655+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.051 seconds
[2023-03-05T13:37:59.819+0000] {processor.py:153} INFO - Started process (PID=17128) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:37:59.822+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:37:59.824+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:37:59.824+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:37:59.839+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:37:59.836+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:37:59.839+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:37:59.861+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.049 seconds
[2023-03-05T13:38:30.168+0000] {processor.py:153} INFO - Started process (PID=17352) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:38:30.171+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:38:30.172+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:38:30.172+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:38:30.204+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:38:30.201+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:38:30.205+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:38:30.261+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.101 seconds
[2023-03-05T13:39:00.419+0000] {processor.py:153} INFO - Started process (PID=17585) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:39:00.429+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:39:00.435+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:39:00.434+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:39:00.490+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:39:00.482+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:39:00.491+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:39:00.539+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.140 seconds
[2023-03-05T13:39:30.664+0000] {processor.py:153} INFO - Started process (PID=17812) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:39:30.669+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:39:30.673+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:39:30.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:39:30.720+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:39:30.715+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:39:30.722+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:39:30.821+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.166 seconds
[2023-03-05T13:40:01.410+0000] {processor.py:153} INFO - Started process (PID=18050) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:40:01.412+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:40:01.412+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:40:01.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:40:01.423+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:40:01.420+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:40:01.424+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:40:01.456+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.049 seconds
[2023-03-05T13:40:32.117+0000] {processor.py:153} INFO - Started process (PID=18260) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:40:32.120+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:40:32.123+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:40:32.123+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:40:32.167+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:40:32.154+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:40:32.169+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:40:32.213+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.104 seconds
[2023-03-05T13:41:02.798+0000] {processor.py:153} INFO - Started process (PID=18471) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:41:02.802+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:41:02.804+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:41:02.804+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:41:02.837+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:41:02.830+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:41:02.838+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:41:02.889+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.106 seconds
[2023-03-05T13:41:34.197+0000] {processor.py:153} INFO - Started process (PID=18707) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:41:34.203+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:41:34.205+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:41:34.205+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:41:34.223+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:41:34.221+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:41:34.224+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:41:34.275+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.082 seconds
[2023-03-05T13:42:04.379+0000] {processor.py:153} INFO - Started process (PID=18925) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:42:04.381+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:42:04.382+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:42:04.382+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:42:04.397+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:42:04.394+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:42:04.398+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:42:04.420+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.044 seconds
[2023-03-05T13:42:35.211+0000] {processor.py:153} INFO - Started process (PID=19129) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:42:35.218+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:42:35.221+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:42:35.221+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:42:35.245+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:42:35.242+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:42:35.246+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:42:35.302+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.101 seconds
[2023-03-05T13:43:05.676+0000] {processor.py:153} INFO - Started process (PID=19353) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:43:05.683+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:43:05.685+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:43:05.685+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:43:05.709+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:43:05.704+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:43:05.710+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:43:05.754+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.088 seconds
[2023-03-05T13:43:36.027+0000] {processor.py:153} INFO - Started process (PID=19577) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:43:36.030+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:43:36.032+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:43:36.032+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:43:36.071+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:43:36.067+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:43:36.073+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:43:36.146+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.142 seconds
[2023-03-05T13:44:06.687+0000] {processor.py:153} INFO - Started process (PID=19811) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:44:06.691+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:44:06.707+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:44:06.706+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:44:06.763+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:44:06.750+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:44:06.765+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:44:06.831+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.156 seconds
[2023-03-05T13:44:37.742+0000] {processor.py:153} INFO - Started process (PID=20037) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:44:37.748+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:44:37.752+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:44:37.751+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:44:37.795+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:44:37.788+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:44:37.798+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:44:37.898+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.170 seconds
[2023-03-05T13:45:08.693+0000] {processor.py:153} INFO - Started process (PID=20260) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:45:08.696+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:45:08.699+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:45:08.699+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:45:08.739+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:45:08.735+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:45:08.741+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:45:08.809+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.139 seconds
[2023-03-05T13:45:57.572+0000] {processor.py:153} INFO - Started process (PID=20495) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:45:57.578+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:45:57.580+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:45:57.580+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:45:57.656+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:45:57.636+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:45:57.663+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:45:57.735+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.168 seconds
[2023-03-05T13:46:27.857+0000] {processor.py:153} INFO - Started process (PID=20719) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:46:27.860+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:46:27.861+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:46:27.861+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:46:27.877+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:46:27.875+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:46:27.878+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:46:27.900+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.048 seconds
[2023-03-05T13:46:58.076+0000] {processor.py:153} INFO - Started process (PID=20926) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:46:58.078+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:46:58.080+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:46:58.080+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:46:58.104+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:46:58.100+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:46:58.109+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:46:58.187+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.117 seconds
[2023-03-05T13:47:29.366+0000] {processor.py:153} INFO - Started process (PID=21147) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:47:29.371+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:47:29.372+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:47:29.372+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:47:29.399+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:47:29.396+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:47:29.401+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:47:29.438+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.082 seconds
[2023-03-05T13:47:59.601+0000] {processor.py:153} INFO - Started process (PID=21374) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:47:59.603+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:47:59.604+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:47:59.604+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:47:59.617+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:47:59.614+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:47:59.617+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:47:59.639+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.042 seconds
[2023-03-05T13:48:30.665+0000] {processor.py:153} INFO - Started process (PID=21578) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:48:30.701+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:48:30.710+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:48:30.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:48:31.015+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:48:30.933+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:48:31.059+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:48:33.561+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 2.949 seconds
[2023-03-05T13:49:06.206+0000] {processor.py:153} INFO - Started process (PID=21802) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:49:06.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:49:06.213+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:49:06.213+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:49:06.249+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:49:06.244+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:49:06.251+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:49:06.701+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.502 seconds
[2023-03-05T13:49:37.658+0000] {processor.py:153} INFO - Started process (PID=22026) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:49:37.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:49:37.664+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:49:37.664+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:49:37.694+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:49:37.685+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:49:37.698+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:49:37.770+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.120 seconds
[2023-03-05T13:50:08.560+0000] {processor.py:153} INFO - Started process (PID=22249) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:50:08.565+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:50:08.574+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:50:08.573+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:50:08.611+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:50:08.601+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:50:08.617+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:50:08.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.124 seconds
[2023-03-05T13:50:38.934+0000] {processor.py:153} INFO - Started process (PID=22484) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:50:38.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:50:38.947+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:50:38.946+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:50:38.999+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:50:38.979+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:50:39.001+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:50:39.062+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.135 seconds
[2023-03-05T13:51:09.172+0000] {processor.py:153} INFO - Started process (PID=22708) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:51:09.176+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:51:09.178+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:51:09.178+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:51:09.199+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:51:09.196+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:51:09.199+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:51:09.230+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.067 seconds
[2023-03-05T13:51:39.544+0000] {processor.py:153} INFO - Started process (PID=22932) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:51:39.549+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:51:39.551+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:51:39.551+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:51:39.612+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:51:39.606+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:51:39.618+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:51:39.678+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.149 seconds
[2023-03-05T13:52:10.196+0000] {processor.py:153} INFO - Started process (PID=23168) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:52:10.204+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:52:10.207+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:52:10.206+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:52:10.232+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:52:10.230+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:52:10.233+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:52:10.265+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.076 seconds
[2023-03-05T13:52:40.601+0000] {processor.py:153} INFO - Started process (PID=23391) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:52:40.605+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:52:40.607+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:52:40.607+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:52:40.630+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:52:40.625+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:52:40.634+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:52:40.702+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.111 seconds
[2023-03-05T13:53:11.338+0000] {processor.py:153} INFO - Started process (PID=23615) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:53:11.346+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:53:11.352+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:53:11.350+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:53:11.403+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:53:11.397+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:53:11.405+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:53:11.502+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.177 seconds
[2023-03-05T13:53:41.658+0000] {processor.py:153} INFO - Started process (PID=23841) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:53:41.662+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:53:41.664+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:53:41.663+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:53:41.697+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:53:41.688+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:53:41.698+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:53:41.739+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.092 seconds
[2023-03-05T13:54:11.843+0000] {processor.py:153} INFO - Started process (PID=24063) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:54:11.847+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:54:11.848+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:54:11.848+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:54:11.866+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:54:11.864+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:54:11.867+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:54:11.907+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.075 seconds
[2023-03-05T13:54:42.417+0000] {processor.py:153} INFO - Started process (PID=24288) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:54:42.426+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:54:42.429+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:54:42.429+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:54:42.478+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:54:42.469+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:54:42.479+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:54:42.524+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.117 seconds
[2023-03-05T13:55:12.772+0000] {processor.py:153} INFO - Started process (PID=24512) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:55:12.776+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:55:12.778+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:55:12.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:55:12.806+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:55:12.803+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 5, in <module>
    from dags.dags.dags.spotify_etl import run_spotify_etl
ModuleNotFoundError: No module named 'dags'
[2023-03-05T13:55:12.807+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:55:12.861+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.097 seconds
[2023-03-05T13:55:29.979+0000] {processor.py:153} INFO - Started process (PID=24700) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:55:29.985+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:55:29.989+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:55:29.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:55:40.230+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:55:40.218+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T13:55:40.232+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:55:40.320+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 10.357 seconds
[2023-03-05T13:56:02.809+0000] {processor.py:153} INFO - Started process (PID=24926) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:56:02.835+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:56:02.863+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:56:02.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:56:04.696+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:56:04.681+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T13:56:04.703+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:56:04.754+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 1.961 seconds
[2023-03-05T13:56:36.398+0000] {processor.py:153} INFO - Started process (PID=25151) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:56:36.435+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:56:36.444+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:56:36.443+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:56:41.534+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:56:41.510+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T13:56:41.539+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:56:41.744+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 5.390 seconds
[2023-03-05T13:58:03.215+0000] {processor.py:153} INFO - Started process (PID=179) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:58:03.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:58:03.225+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:58:03.225+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:58:05.584+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:58:05.573+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T13:58:05.587+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:58:05.642+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 2.438 seconds
[2023-03-05T13:58:36.541+0000] {processor.py:153} INFO - Started process (PID=420) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:58:36.543+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:58:36.545+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:58:36.545+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:58:37.191+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:58:37.184+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T13:58:37.192+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:58:37.225+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.689 seconds
[2023-03-05T13:59:07.416+0000] {processor.py:153} INFO - Started process (PID=645) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:59:07.418+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:59:07.420+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:59:07.420+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:59:07.750+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:59:07.743+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T13:59:07.751+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:59:07.772+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.362 seconds
[2023-03-05T13:59:37.887+0000] {processor.py:153} INFO - Started process (PID=892) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:59:37.888+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T13:59:37.889+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:59:37.889+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:59:38.151+0000] {logging_mixin.py:137} INFO - [2023-03-05T13:59:38.137+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T13:59:38.153+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T13:59:38.199+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.314 seconds
[2023-03-05T14:00:08.358+0000] {processor.py:153} INFO - Started process (PID=1108) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:00:08.363+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:00:08.365+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:00:08.365+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:00:08.651+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:00:08.640+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:00:08.656+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:00:08.689+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.337 seconds
[2023-03-05T14:00:38.902+0000] {processor.py:153} INFO - Started process (PID=1346) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:00:38.905+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:00:38.907+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:00:38.907+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:00:39.237+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:00:39.234+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:00:39.238+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:00:39.255+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.359 seconds
[2023-03-05T14:01:09.442+0000] {processor.py:153} INFO - Started process (PID=1579) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:01:09.445+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:01:09.447+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:01:09.447+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:01:09.777+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:01:09.770+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:01:09.779+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:01:09.862+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.423 seconds
[2023-03-05T14:01:40.730+0000] {processor.py:153} INFO - Started process (PID=1823) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:01:40.732+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:01:40.734+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:01:40.734+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:01:41.082+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:01:41.075+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:01:41.084+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:01:41.104+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.382 seconds
[2023-03-05T14:02:11.184+0000] {processor.py:153} INFO - Started process (PID=2047) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:02:11.188+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:02:11.189+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:02:11.189+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:02:11.433+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:02:11.430+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:02:11.434+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:02:11.456+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.277 seconds
[2023-03-05T14:02:42.093+0000] {processor.py:153} INFO - Started process (PID=2283) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:02:42.097+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:02:42.099+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:02:42.098+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:02:42.360+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:02:42.355+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:02:42.360+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:02:42.379+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.292 seconds
[2023-03-05T14:03:12.484+0000] {processor.py:153} INFO - Started process (PID=2518) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:03:12.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:03:12.488+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:03:12.488+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:03:13.610+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:03:13.588+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:03:13.654+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:03:13.748+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 1.270 seconds
[2023-03-05T14:03:44.004+0000] {processor.py:153} INFO - Started process (PID=2755) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:03:44.007+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:03:44.009+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:03:44.009+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:03:44.319+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:03:44.308+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:03:44.322+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:03:44.348+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.353 seconds
[2023-03-05T14:04:15.254+0000] {processor.py:153} INFO - Started process (PID=2981) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:04:15.256+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:04:15.259+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:04:15.258+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:04:15.530+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:04:15.526+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:04:15.531+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:04:15.546+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.302 seconds
[2023-03-05T14:04:45.706+0000] {processor.py:153} INFO - Started process (PID=3219) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:04:45.721+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:04:45.726+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:04:45.725+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:04:46.701+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:04:46.690+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:04:46.704+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:04:46.771+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 1.088 seconds
[2023-03-05T14:05:16.858+0000] {processor.py:153} INFO - Started process (PID=3444) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:05:16.860+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:05:16.862+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:05:16.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:05:17.898+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:05:17.876+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:05:17.902+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:05:17.942+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 1.090 seconds
[2023-03-05T14:05:48.404+0000] {processor.py:153} INFO - Started process (PID=3672) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:05:48.408+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:05:48.410+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:05:48.410+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:05:49.072+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:05:49.064+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:05:49.073+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:05:49.161+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.761 seconds
[2023-03-05T14:06:20.133+0000] {processor.py:153} INFO - Started process (PID=3904) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:06:20.138+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:06:20.144+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:06:20.144+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:06:21.637+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:06:21.590+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:06:21.653+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:06:21.756+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 1.633 seconds
[2023-03-05T14:06:52.760+0000] {processor.py:153} INFO - Started process (PID=4132) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:06:52.774+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:06:52.780+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:06:52.780+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:06:53.571+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:06:53.562+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:06:53.573+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:06:53.675+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.939 seconds
[2023-03-05T14:07:24.026+0000] {processor.py:153} INFO - Started process (PID=4375) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:07:24.029+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:07:24.031+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:07:24.031+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:07:24.449+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:07:24.434+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:07:24.459+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:07:24.537+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.514 seconds
[2023-03-05T14:07:54.803+0000] {processor.py:153} INFO - Started process (PID=4591) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:07:54.810+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:07:54.813+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:07:54.813+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:07:55.161+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:07:55.153+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:07:55.163+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:07:55.191+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.395 seconds
[2023-03-05T14:08:25.395+0000] {processor.py:153} INFO - Started process (PID=4821) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:08:25.398+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:08:25.398+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:08:25.398+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:08:25.681+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:08:25.678+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:08:25.682+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:08:25.699+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.308 seconds
[2023-03-05T14:08:56.579+0000] {processor.py:153} INFO - Started process (PID=5054) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:08:56.585+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:08:56.590+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:08:56.589+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:08:57.195+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:08:57.182+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:08:57.198+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:08:57.236+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.666 seconds
[2023-03-05T14:09:27.996+0000] {processor.py:153} INFO - Started process (PID=5281) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:09:27.998+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:09:28.000+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:09:28.000+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:09:28.277+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:09:28.273+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:09:28.278+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:09:28.296+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.307 seconds
[2023-03-05T14:09:58.708+0000] {processor.py:153} INFO - Started process (PID=5507) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:09:58.711+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:09:58.712+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:09:58.712+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:09:59.190+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:09:59.182+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:09:59.194+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:09:59.255+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.551 seconds
[2023-03-05T14:10:29.356+0000] {processor.py:153} INFO - Started process (PID=5742) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:10:29.359+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:10:29.361+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:10:29.361+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:10:29.770+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:10:29.759+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:10:29.775+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:10:29.862+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 0.510 seconds
[2023-03-05T14:11:01.937+0000] {processor.py:153} INFO - Started process (PID=5974) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:11:01.941+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:11:01.944+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:11:01.943+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:11:02.895+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:11:02.875+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:11:02.900+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:11:03.011+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 1.085 seconds
[2023-03-05T14:11:33.747+0000] {processor.py:153} INFO - Started process (PID=6192) to work on /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:11:33.753+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/spotify_dag.py for tasks to queue
[2023-03-05T14:11:33.756+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:11:33.756+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:11:34.937+0000] {logging_mixin.py:137} INFO - [2023-03-05T14:11:34.925+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/spotify_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/spotify_dag.py", line 7, in <module>
    from spotify_etl import run_spotify_etl
  File "/opt/airflow/dags/spotify_etl.py", line 87, in <module>
    print(tabulate(song_df, headers='keys', tablefmt='psql'))
NameError: name 'song_df' is not defined
[2023-03-05T14:11:34.940+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/spotify_dag.py
[2023-03-05T14:11:34.998+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/spotify_dag.py took 1.276 seconds
